Feature/radix UI modal
apptension/saas-boilerplate pull request #187
Opened 2023-06-05 12:07 UTC by bielsky0

### Please check if the PR fulfills these requirements

- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added / updated (for bug fixes / features)

### What kind of change does this PR introduce?

Migrate from styled components to radix ui

2023-06-06 11:14 UTC, mkleszcz requested changes

2023-06-06 11:14 UTC, mkleszcz commented on packages/webapp-libs/webapp-core/src/components/modal/modal.component.tsx
> +const Dialog = DialogPrimitive.Root;
We should keep the file naming consistent with the component name so either change the file name or change the component name

2023-06-07 10:54 UTC, mkleszcz requested changes

2023-06-07 10:54 UTC, mkleszcz commented on packages/webapp-libs/webapp-core/src/components/dialog/dialog.component.tsx
Move each component in separate file, please ;)

2023-06-07 10:54 UTC, mkleszcz commented on packages/webapp-libs/webapp-core/src/components/dialog/dialog.styles.ts
Is this file used?

2023-06-12 07:08 UTC, mkleszcz commented on packages/webapp-libs/webapp-core/src/components/dialog/__tests__/dialog.component.spec.tsx
> +        <DialogContent> {content}</DialogContent>
This space is a typo?;)

2023-06-12 07:10 UTC, bielsky0 commented on packages/webapp-libs/webapp-core/src/components/dialog/__tests__/dialog.component.spec.tsx
> +        <DialogContent> {content}</DialogContent>
yep

2023-06-12 08:41 UTC, merged